admissionController:
  replicas: 2
  resources:
    limits:
      cpu: 750m
      memory: 768Mi
    requests:
      cpu: 200m
      memory: 256Mi

backgroundController:
  replicas: 2
  resources:
    limits:
      cpu: 750m
      memory: 768Mi
    requests:
      cpu: 200m
      memory: 256Mi

cleanupController:
  replicas: 2
  resources:
    limits:
      cpu: 300m
      memory: 384Mi
    requests:
      cpu: 100m
      memory: 128Mi

reportsController:
  replicas: 2
  resources:
    limits:
      cpu: 750m
      memory: 768Mi
    requests:
      cpu: 200m
      memory: 256Mi
