---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    environment: tst
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-ingress
  labels:
    environment: tst
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    environment: tst
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-ingress
  labels:
    environment: tst
    istio-injection: enabled
