apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    environment: int
---
apiVersion: v1
kind: Namespace
metadata:
  name: kyverno
  labels:
    environment: int
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
  labels:
    environment: int
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    environment: int
